name: Build Feature Artifacts
on:
  push:
    branches:
      - feature**
      - feat**

jobs:
  build-core-microservices:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Print system settings
        run: |
          printf "$(java -version)\n"
          printf "$(mvn -version)\n"

      - name: Build hr-worker
        run: |
          cd hr-worker/
          
          printf "building hr-worker artifact!\n"
          printf "current_dir: $PWD\n"
          ls -ll
          
          mvn clean install \
          --threads 2C \
          --file pom.xml

      - name: Build hr-payroll
        run: |
          cd hr-payroll/
          
          printf "building hr-payroll artifact!\n"
          printf "current_dir: $PWD\n"
          ls -ll
          
          mvn clean install \
          --threads 2C \
          --file pom.xml          
